### ISSUE TITLE
Can't create superuser and other problems in UnRaid

### ISSUE THREAD

**Issue by reitenth** [eitchtee/WYGIWYH#134]
ive tried running `docker compose exec -it web python manage.py createsuperuser`

and ill i get is `service "web" is not running.` i can get to the port with login page though

**Comment by eitchtee** [comment]
If you've renamed the `web` service you need to replace `web` in the command with the name you used. For example:

```yaml
services:
  web: <---- see if this is called web, if it isn't replace web in the command with the name that's here
    image: eitchtee/wygiwyh:latest
```

Alternatively you can use:

`docker exec -it wygiwyh_server python manage.py createsuperuser`

Just replace `wygiwyh_server` with your wygiwyh container name (not the postgres one).

If you still have problems, could you share your docker-compose.yml file? Let me know how it goes.
