### ISSUE TITLE
CSV Import function

### ISSUE THREAD

**Issue by lo97** [eitchtee/WYGIWYH#41]
Hi, I love the project but it would be very useful it there would be an import (and, in the future export) function, either from csv or excel. This could be useful both for accounts, currencies etc. and for transactions

**Comment by eitchtee** [comment]
Yes! That's definitely something I want to do.

Do you have any examples of what you want to import? No need for the actual data of course, just the headers and if possible some anonymized data.

I've been thinking about how to implement this, would be nice to know how this data is usually presented.

**Comment by crazybob1215** [comment]
I'd really like to see this feature too! Here's a (sanitized) example of the export my bank provides when I ask for a csv.


<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Aaron/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Aaron/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">


Account Name : Checking |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | --
Account   Number : 11111111111 |   |   |   |   |   |   |  
Date Range :   01/01/2025-01/15/2025 |   |   |   |   |   |  
Transaction Number | Date | Description | Memo | Amount Debit | Amount Credit | Balance | Check Number | Fees
123456 | 1/10/2025 | Withdrawal ATM | Arbitrary note about what this money is doing | -50 |   | 850 |   |  
121212 | 1/2/2025 | Withdrawal Electric Bill | I use too much electricity for self-hosting | -100 |   | 900 |   |  
96024 | 1/1/2025 | Deposit Paycheck | Paycheck for work I definitely did |   | 1000 | 1000 |   |  



</body>

</html>

**Comment by Inrego** [comment]
Have you given thought to automatically import bank transactions through api's?

**Comment by madiele** [comment]
This are the csv headers exported by the default export of firefly (though it's possible to export more stuff by using the command line)
``` user_id,group_id,journal_id,created_at,updated_at,group_title,type,amount,foreign_amount,currency_code,foreign_currency_code,description,date,source_name,source_iban,source_type,destination_name,destination_iban,destination_type,reconciled,category,budget,bill,tags,notes,sepa_cc,sepa_ct_op,sepa_ct_id,sepa_db,sepa_country,sepa_ep,sepa_ci,sepa_batch_id,external_url,interest_date,book_date,process_date,due_date,payment_date,invoice_date,recurrence_id,internal_reference,bunq_payment_id,import_hash,import_hash_v2,external_id,original_source,recurrence_total,recurrence_count,recurrence_date
```

**Comment by madiele** [comment]
I would also add that while writing an import script the biggest hurdle I had is that a reference Id is missing from the API: basically an ID that I can give that uniquely identity an imported transaction, if I run the import and give the same import id the import shoud update the old record or ignore it

This way it's possible to retry the import many times without accidentally duplicating fields, so for a firefly import I could use the journal ID for this scope

**Comment by Inrego** [comment]
I don't know which API you're referencing. But I think most api's would have a transaction ID. I know that GoCardless does

**Comment by madiele** [comment]
I was mentioning WYGIWYH current API, since I developed a firefly import script already and played with it already

https://github.com/eitchtee/WYGIWYH/discussions/49

**Comment by eitchtee** [comment]
> I would also add that while writing an import script the biggest hurdle I had is that a reference Id is missing from the API: basically an ID that I can give that uniquely identity an imported transaction, if I run the import and give the same import id the import shoud update the old record or ignore it and give an error (for the API I prefer error, if I can get a transaction by reference Id via API I could write the update manually then)
> 
> This way it's possible to retry the import many times without accidentally duplicating fields, so for a firefly import I could use the journal ID for this scope

That's planned. I'm adding a external_note and external_id fields, that are only accessible via imports and the API, the last is unique meaning it would error out if you try to set two transactions with the same one.

**Comment by eitchtee** [comment]
Version 0.7.0 brings the beta version of Import and a bunch of other changes.

Please check the release notes for what you need to do to upgrade and use this function: https://github.com/eitchtee/WYGIWYH/releases/tag/0.7.0 and https://github.com/eitchtee/WYGIWYH/wiki/Import for documentation (could be improved)

Unfortunately this was a more complex task than I predicted, which led to a less interactive interface.

Leaving this issue open for now to get some feedback. Please open a new issue for bugs and new features.

**Comment by crazybob1215** [comment]
@eitchtee I'm testing the import function now, and I'm running into an issue. Instead of using one field for transaction amounts, they list the amount as either "Amount Debit" or "Amount Credit". I figure I can use the current import scheme by doing this:

```
   amount:
    target: amount
    required: true
    transformations:
      - type: merge
        fields: "Amount Debit" "Amount Credit"
        separator: ""

  type:
    source: amount
    target: type
    detection_method: sign
```

The problem is that when I try to create the import profile, it throws this error:
> Invalid YAML Configuration: while parsing a block mapping in "<unicode string>", line 37, column 9: - type: merge ^ expected <block end>, but found '<scalar>' in "<unicode string>", line 38, column 32: fields: "Amount Debit" "Amount Credit" ^

I've tried adding a comma as a separator, removing the space, both at the same time... It doesn't matter, I still get the same error. What is the proper formatting for listing the fields to merge?

**Comment by eitchtee** [comment]
@crazybob1215 you have to use a list:

```yaml
- type: merge
   fields:
    - "Amount Debit"
    - "Amount Credit"
   separator: ""
```

or

```yaml
- type: merge
   fields: ["Amount Debit", "Amount Credit"]
   separator: ""
```

This is poorly documented on the wiki, I will update it.

Let me know how it goes.

**Comment by eitchtee** [comment]
@crazybob1215 it should look something like this in the end:

```yaml
settings:
  file_type: csv
  delimiter: ","
  encoding: utf-8
  skip_lines: 2
  importing: transactions
  trigger_transaction_rules: true
  skip_errors: true

mapping:
  account:
    target: account
    default: Main Account
    type: name

  date:
    target: date
    source: Date
    format: "%m/%d/%Y"

  amount:
    target: amount
    transformations:
      - type: merge
        fields: ["Amount Debit", "Amount Credit"]
        separator: ""

  description:
    target: description
    source: Description

  type:
    target: type
    detection_method: sign
    transformations:
      - type: merge
        fields: ["Amount Debit", "Amount Credit"]
        separator: ""

  notes:
    target: notes
    source: Memo

  internal_id:
    target: internal_id
    source: Transaction Number

  is_paid:
    target: is_paid
    detection_method: always_paid
    
deduplication:
  - type: compare
    fields:
      - internal_id
    match_type: strict
```

**Comment by crazybob1215** [comment]
Perfect, that cleared the error. I briefly ran into a permissions issue for the temp folder, but I'm past that now. I'm now seeing an error:

> wygiwyh_procrastinate  | apps.transactions.models.Transaction.account.RelatedObjectDoesNotExist: Transaction has no account.

In the export from my bank, the account name is only listed once in the header, not on each line. I thought I had this covered by not setting a "source" for the account mapping. Here's what my full import profile looks like, and an example line from the csv:

```
settings:
  file_type: csv
  delimiter: ","
  encoding: utf-8
  skip_lines: 3
  importing: transactions
  trigger_transaction_rules: true
  skip_errors: true

mapping:
  account:
    target: account
    default: BANK - Checking
    type: name

  internal_id:
    target: internal_id
    source: "Transaction Number"

  date:
    target: date
    source: Date
    format: "%m/%d/%Y"

  description:
    target: description
    source: Description

  notes:
    target: notes
    source: Memo

  amount:
    target: amount
    required: true
    transformations:
      - type: merge
        fields: ["Amount Debit", "Amount Credit"]
        separator: ""

  type:
    source: amount
    target: type
    detection_method: sign

deduplication:
  - type: compare
    fields:
      - internal_id
    match_type: strict
```

```
Transaction Number,Date,Description,Memo,Amount Debit,Amount Credit,Balance,Check Number,Fees  
"12345",01/27/2025,"Withdrawal to Foo","Credit card payment",-500.00,,"1000.00",,
```

**Comment by eitchtee** [comment]
@crazybob1215 your YAML looks pretty clean to me.

The error you mentioned happens when an account with the provided name or id can't be found, are you sure "BANK - Checking" (or the original value you're using) exists on your instace? Try quoting it just in case.

Also you might want to change you `type` mapping to:

```yaml
type:
    target: type
    detection_method: sign
    transformations:
      - type: merge
        fields: ["Amount Debit", "Amount Credit"]
        separator: ""
```

Currently you can't source a mapped value, just CSV headers.

**Comment by crazybob1215** [comment]
Ah, I thought I was targeting the account name correctly, but it is actually just "Checking" and not "BANK - Checking".

As for the type mapping in your example, shouldn't the target be `amount` and not `type`? If I set it to `type`, I get what appears to be a format handling error. When set to `amount` it runs successfully.

**Comment by eitchtee** [comment]
Glad it worked.

> As for the type mapping in your example, shouldn't the target be `amount` and not `type`? If I set it to `type`, I get what appears to be a format handling error. When set to `amount` it runs successfully.

> 2\. It's importing all of the transactions as expenses. The values listed in the csv under "Amount Debit" are negative and "Amount Credit" are positive, so I would expect the `detection method: sign` to correctly identify the transactions but apparently something isn't correct there.

You need to have two different mappings:

```yaml
  amount:
    target: amount
    transformations:
      - type: merge
        fields: ["Amount Debit", "Amount Credit"]
        separator: ""
```

and

```yaml
  type:
    target: type
    detection_method: sign
    transformations:
      - type: merge
        fields: ["Amount Debit", "Amount Credit"]
        separator: ""
```

The first represents the transaction amount, internally WYGIWYH stores all amounts as positive values. The second, represents the type of the transaction, if it's Income or Expense.

In the YAML you shared, `type` is sourcing from "amount", which isn't a header in your csv, so it will be ignored silently and all your imported transactions will be added with the database default of Expense.

My suggestion is to have both `amount` and `type` with the same transformation, this way type can be inferred by sign, i.e. if it's a negative value, it will be an Expense, if it's a positive value, it will be treated as Income.

This definitely could be improved.

---

> 1. From the Overview (monthly) page, if I change the `Order by` to `Newest first` I can't see any of the imported transactions. I can see them with it set to `Default` or `Oldest first`.

What we use for caching database queries is not playing nice with our task scheduler, I'm aware and looking for a fix, you can click the Yellow Bust icon on the navbar and select `Clear cache`, everything should show up after this.

**Comment by eitchtee** [comment]
Also, if you enabled SOFT_DELETE, you might want to go to Management > Django Admin > Transactions and Hard Delete the transactions you imported so you can re-import them with the correct type.

Select them all and choose the action shown below:

![Image](https://github.com/user-attachments/assets/7ad4e40d-16b4-4ebc-bc53-342647a87498)

If you didn't enable it, just deleting the wrong transactions should be enough to re-import.

**Comment by crazybob1215** [comment]
Adding both the `amount` and `type` mappings and using the `Clear Cache` button seems to have fixed both of the issues. Thanks for all the help with getting my head wrapped around this!

**Comment by eitchtee** [comment]
No problem at all @crazybob1215 , this actually gave me some ideas on how to improve the config, stay tuned.

**Comment by eitchtee** [comment]
@crazybob1215 you might want to upgrade to [0.8.0](https://github.com/eitchtee/WYGIWYH/releases/tag/0.8.0) and use a single container setup, make sure to read the release notes to know more about it. It should fix the caching problem.

**Comment by crazybob1215** [comment]
@eitchtee Upgraded to 0.8.0. Tried a couple imports and that seems to be working fine, also the caching seems to be working as well. I noticed that it is remembering my `Order by` setting as I change pages now too, which is pretty handy.

**Comment by eitchtee** [comment]
> Seems a lot of manual setup, I thought just drop csv and we are good to go. Usually something like pre-made example template, and we download it , then just fill in our data, and import to it, but we need to setup yaml,etc.
> 
> This app seems like have all the feature I need, just need to play around to know it better, really appreciate all the things u do mate, thanks.

@lucius100 unfortunately CSVs are universal, but not standardized, so there's some complexity that comes with that. We do have a presets feature to try to get away with some of these complexities, but it's lacking on presets right now, hopefully the community can pick up on it and share the configuration for their banks and apps. If you need help with your YAML config you can open an issue, just share how your data is presented and I will be happy to help.

Hope you can try it out and like it.

**Comment by andremohrmann** [comment]
Not sure if I'm misunderstanding the yaml requirements or something else, but I get this error trying to import my csv:
> [2025-02-05 21:52:41] INFO: Starting import process
> [2025-02-05 21:52:41] INFO: Skipped 1 initial lines
> [2025-02-05 21:52:41] INFO: Starting import with 57 rows
> [2025-02-05 21:52:41] ERROR: Fatal error processing row 1: Required field date is missing
> [2025-02-05 21:52:41] ERROR: Import failed: Required field date is missing

My yaml configuration:
```
settings:
  file_type: csv
  delimiter: ","
  encoding: utf-8
  skip_lines: 1
  importing: transactions
  trigger_transaction_rules: true
  skip_errors: false


mapping:
  date:
    target: date
    source: "Timestamp"
    format: "%d/%m/%Y"
  amount:
    target: amount
    source: Amount
    required: true
  description:
    target: description
    source: "TransactionDescription"
  

deduplication:
  - type: compare
    fields:
      - internal_id
    match_type: strict
```

My transactions csv file:
```
Timestamp,TransactionDescription,Currency,Amount,To Currency,To Amount,Native Currency,Native Amount,Native Amount (in USD),Transaction Kind,Transaction Hash
30/01/2025,Purchase01,EUR,-20,,,EUR,-20,-20,9214385,,
30/01/2025,Purchase02,EUR,-544,,,EUR,-544,-569,0631272,,
30/01/2025,EUR Deposit,EUR,258,,,EUR,258,269,8865567,,
30/01/2025,Purchase03,EUR,-14,9,,,EUR,-14,9,-15,58647168,,
```

What am I missing here?

**Comment by eitchtee** [comment]
> What am I missing here?

@andremohrmann If the first line of your CSV is the header as in your example, you can set `skip_lines` to 0. Lines should be skipped only to reach the header in the file. This is probably why date is missing, because it couldn't find the given header.

Also, you're missing a few required fields and optional fields:

```yaml
  internal_id:
    target: internal_id
    transformations:
        - type: hash
          fields: ["Timestamp", "TransactionDescription", "Amount"]
```
This will hash the fields and add them to internal_id so you don't re-import then in the future. If `Transaction Hash` is present on your file but omitted here, you could use that instead, then you won't need the transformations.

```yaml
type:
    source: Amount
    target: "type"
    detection_method: sign
```
This will add a income or expense based on the amount sign

```yaml
account:
    target: account
    source: "Currency"
    type: name
    transformations:
        - type: "replace"
          pattern: "EUR"
          replacement: "<YOUR EUR ACCOUNT NAME>"
          exclusive: true
```
This should add all transactions with currency EUR to the account you set.

```yaml
  is_paid:
    target: is_paid
    detection_method: always_paid
```
This will make all imported transactions paid by default.


That should be it. Let me know how it goes.

Remembering the spec is still in beta, if you need something specific that can't be done currently or find some bug you can open an issue and I will be happy to check it out.

**Comment by andremohrmann** [comment]
This is my full import yaml now:
```yaml
settings:
  file_type: csv
  delimiter: ","
  encoding: utf-8
  skip_lines: 0
  importing: transactions
  trigger_transaction_rules: true
  skip_errors: false

mapping:
  account:
    target: account
    source: "Currency"
    type: name
    transformations:
        - type: "replace"
          pattern: "EUR"
          replacement: "AM"
          exclusive: true
  amount:
    target: amount
    source: "Amount"
    required: true
  description:
    target: description
    source: "TransactionDescription"
  internal_id:
    target: internal_id
    transformations:
        - type: hash
          fields: ["Timestamp", "TransactionDescription", "Amount"]  
  date:
    target: date
    source: "Timestamp"
    format: "%d/%m/%Y"
  is_paid:
    target: is_paid
    detection_method: always_paid

deduplication:
  - type: compare
    fields:
      - internal_id
    match_type: strict
```

I still get this error:
```
2025-02-06 21:20:20 2025-02-06 20:20:20,790 INFO    procrastinate.worker Starting job apps.import_app.tasks.process_import[7](file_path='/usr/src/app/temp/card_transactions_record_02052025_221347_TTLEnjQ.csv', import_run_id=4)
2025-02-06 21:20:20 2025-02-06 20:20:20,853 ERROR   procrastinate.worker Job apps.import_app.tasks.process_import[7](file_path='/usr/src/app/temp/card_transactions_record_02052025_221347_TTLEnjQ.csv', import_run_id=4) ended with status: Error, lasted 0.062 s
2025-02-06 21:20:20 Traceback (most recent call last):
2025-02-06 21:20:20   File "/usr/src/app/apps/import_app/services/v1.py", line 615, in process_file
2025-02-06 21:20:20     self._process_csv(file_path)
2025-02-06 21:20:20   File "/usr/src/app/apps/import_app/services/v1.py", line 590, in _process_csv
2025-02-06 21:20:20     self._process_row(row, row_number)
2025-02-06 21:20:20   File "/usr/src/app/apps/import_app/services/v1.py", line 529, in _process_row
2025-02-06 21:20:20     mapped_data = self._map_row(row)
2025-02-06 21:20:20                   ^^^^^^^^^^^^^^^^^^
2025-02-06 21:20:20   File "/usr/src/app/apps/import_app/services/v1.py", line 513, in _map_row
2025-02-06 21:20:20     raise ValueError(f"Required field {field} is missing")
2025-02-06 21:20:20 ValueError: Required field date is missing
2025-02-06 21:20:20 
2025-02-06 21:20:20 During handling of the above exception, another exception occurred:
2025-02-06 21:20:20 
2025-02-06 21:20:20 Traceback (most recent call last):
2025-02-06 21:20:20   File "/usr/local/lib/python3.11/site-packages/procrastinate/worker.py", line 281, in run_job
2025-02-06 21:20:20     task_result = await await_func(*job_args, **job.task_kwargs)
2025-02-06 21:20:20                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-06 21:20:20   File "/usr/local/lib/python3.11/site-packages/procrastinate/utils.py", line 108, in sync_to_async
2025-02-06 21:20:20     return await sync.sync_to_async(func, thread_sensitive=False)(*args, **kwargs)
2025-02-06 21:20:20            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-06 21:20:20   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 468, in __call__
2025-02-06 21:20:20     ret = await asyncio.shield(exec_coro)
2025-02-06 21:20:20           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-06 21:20:20   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
2025-02-06 21:20:20     result = self.fn(*self.args, **self.kwargs)
2025-02-06 21:20:20              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-06 21:20:20   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 522, in thread_handler
2025-02-06 21:20:20     return func(*args, **kwargs)
2025-02-06 21:20:20            ^^^^^^^^^^^^^^^^^^^^^
2025-02-06 21:20:20   File "/usr/src/app/apps/import_app/tasks.py", line 17, in process_import
2025-02-06 21:20:20     import_service.process_file(file_path)
2025-02-06 21:20:20   File "/usr/src/app/apps/import_app/services/v1.py", line 629, in process_file
2025-02-06 21:20:20     raise Exception("Import failed")
2025-02-06 21:20:20 Exception: Import failed
```

I even tried setting up a fresh instance with an empty database and just added a currency and an account. Then tried the import again. Same error.
