### ISSUE TITLE
Add Exchange Rate Giving Error

### ISSUE THREAD

**Issue by rjdainty1** [eitchtee/WYGIWYH#80]
When attempting to add a new exchange rate, selecting a date / time in the popup appears to enter an incorrectly formatted date / time.

<img width="566" alt="Image" src="https://github.com/user-attachments/assets/02ca670f-8c5d-4b0e-b799-6c67e7502136" />

The above image shows the date / time entered, trying to submit an exchange rate with this date / time gives the error message:-
<img width="478" alt="Image" src="https://github.com/user-attachments/assets/13ca9f81-7a29-445a-8320-595281fb59d8" />

However, reformatting the date / time, correcting the time to HH:MM and removing 'PM' works fine.

The date / time settings are as follows:-
<img width="627" alt="Image" src="https://github.com/user-attachments/assets/09772acd-cf31-4a5d-a01c-ec1d38bc84c5" />

Just a few more details about the system / Docker just in case they help...

`sudo docker exec -it wygiwyh ls -l /etc/localtime`
`lrwxrwxrwx 1 root root 27 Jan 13 00:00 /etc/localtime -> /usr/share/zoneinfo/Etc/UTC`

`sudo docker exec -it wygiwyh cat /etc/timezone`
`Etc/UTC`

`sudo docker --version`
`Docker version 27.5.0, build a187fa5`

docker-compose.yml
```
  wygiwyh:
    image: eitchtee/wygiwyh:latest
    container_name: wygiwyh
    command: /start
    ports:
      - "8001:8000"
    env_file:
      - .env2
    depends_on:
      - postgresql
    volumes:
      - ./wygiwyh:/usr/src/app/temp/
    restart: unless-stopped
```
